openapi: 3.1.0
info:
  title: Issue Tracker API
  version: 1.0.0
  description: API for the Issue Tracker application

servers:
  - url: http://localhost:3000/api/
    description: Local development server

paths:
  /issue:
    get:
      summary: Get all issues
      responses:
        '200':
          description: A list of issues
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Issue'
    post:
      summary: Create a new issue
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateIssueRequest'
      responses:
        '201':
          description: Issue created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Issue'
  /issue/status:
    get:
      summary: Get all issue statuses
      responses:
        '200':
          description: A list of issue statuses
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/IssueStatus'
    post:
      summary: Create a new issue status
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateIssueStatusRequest'
      responses:
        '201':
          description: Issue status created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IssueStatus'
components:
  schemas:
    Issue:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: The unique identifier for the issue
        title:
          type: string
          description: The title of the issue
        description:
          type: string
          description: The description of the issue
        status:
          type: string
          description: The status of the issue
        createdAt:
          type: string
          format: date-time
          description: The date and time the issue was created
        updatedAt:
          type: string
          format: date-time
          description: The date and time the issue was last updated
    CreateIssueRequest:
      type: object
      properties:
        title:
          type: string
          description: The title of the issue
        description:
          type: string
          description: The description of the issue
        status_id:
          type: integer
          format: int64
          description: The status of the issue
      required:
        - title
        - description
        - status_id
    IssueStatus:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: The unique identifier for the issue status
        name:
          type: string
          description: The name of the issue status
        description:
          type: string
          description: The description of the issue status
        group:
          type: string
          description: The group of the issue status
    CreateIssueStatusRequest:
      type: object
      properties:
        name:
          type: string
          description: The name of the issue status
        description:
          type: string
          description: The description of the issue status
        group:
          type: string
          description: The group of the issue status
      required:
        - name
        - description
        - group
